name: pendulo
description: Metronome mobile app made in flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_picker:
    git: https://github.com/yangyxd/flutter_picker.git

  soundpool: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
  fonts:
    - family: Computer Modern
      fonts:
        - asset: assets/fonts/cmunbsr.ttf
        - asset: assets/fonts/cmunsx.ttf
          weight: 700
    - family: Bravura
      fonts:
        - asset: assets/fonts/Bravura.otf
        - asset: assets/fonts/BravuraText.otf
